title: "Fabio & Carlotta"
baseurl: "/fabioecarlotta" # se lo metti su GitHub Pages tipo /fabioecarlotta aggiorna questo
url: "https://www.fabioecarlotta.it"     # es. https://tuodominio.it
markdown: kramdown
theme: null

# Dati che puoi riusare nei template
wedding:
  couple_names: "Fabio & Carlotta"
  date: "Sabato 20 Giugno 2026"
  location_line1: "Romagnano, Verona"
  location_line2: "Italy"
  rsvp_link: "#rsvp"

