title: "Fabio & Carlotta"
baseurl: ""
url: "https://www.fabioecarlotta.it"
markdown: kramdown
theme: null

wedding:
  couple_names: "Fabio & Carlotta"
  date: "20th of June 2026"
  location_line1: "Villa Pellegrini"
  location_line2: "Romagnano di Valpantena, Verona"
  rsvp_link: ""

github_username: fabiolucidi
repository: fabiolucidi/fabioecarlotta.github.io
repo_url: https://github.com/fabiolucidi/fabioecarlotta.github.io

