title: "Fabio & Carlotta"
baseurl: "" # se lo metti su GitHub Pages tipo /fabioecarlotta aggiorna questo
url: "https://www.fabioecarlotta.it"     # es. https://tuodominio.it
markdown: kramdown
theme: null

# Dati che puoi riusare nei template
wedding:
  couple_names: "Fabio & Carlotta"
  date: "Sabato 20 Giugno 2026"
  location_line1: "Villa Pellegrini"
  location_line2: "Romagnano di Valpantena, Verona"
  rsvp_link: "https://withjoy.com/fabioecarlotta/rsvp"

